---

# API

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: micro-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-proxy
  template:
    metadata:
      labels:
        app: micro-proxy
    spec:
        containers:
        - name: micro-proxy
          image: eu.gcr.io/tabb-168314/tabb-gateway:latest
          args:
            - "api"
            - "--handler=rpc"
            - "--namespace=tabb.srv"
          env:
          - name: MICRO_API_ADDRESS
            value: ":80"
          - name: VERSION
            value: "26"
          - name: CORS_ALLOWED_HEADERS
            value: "X-Tabb-Place, x-tabb-place"
          - name: CORS_ALLOWED_ORIGINS
            value: "*"
          - name: CORS_ALLOWED_METHODS
            value: "POST"
          ports:
          - containerPort: 80
            name: port
---

apiVersion: v1
kind: Service
metadata:
  name: micro-proxy
spec:
  type: LoadBalancer
  ports:
  - name: api-http
    port: 80
    targetPort: "port"
    protocol: TCP
  selector:
    app: micro-proxy
